language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-Werror"
    - BUILD=~/buildTmp
    - LIBPNG_DOWNLOAD=http://download.sourceforge.net/libpng/libpng-
  matrix:
    - LIBPNG_VERSION=1.2.53
    - LIBPNG_VERSION=1.4.16
    - LIBPNG_VERSION=1.5.22
    - LIBPNG_VERSION=1.6.17
    - LIBPNG_VERSION=1.7.0beta65

matrix:
  allow_failures:
    - env: LIBPNG_VERSION=1.7.0beta65

script:
  - cd $BUILD
  - cmake $TRAVIS_BUILD_DIR
  - make
  - sudo make install

before_script:
  - uname -r
  - lsb_release -a
# kick without checking dependencies
  - sudo dpkg -r --force-depends libpng12-dev
  - sudo dpkg -r --force-depends libpng12-0
  - sudo rm -rf /usr/include/libpng12 /urs/include/png*.h /usr/lib/x86_64-linux-gnu/libpng*
#  - sudo apt-get remove -qq libpng12-0 libpng12-0:i386
  - sudo dpkg --get-selections
  - wget "$LIBPNG_DOWNLOAD$LIBPNG_VERSION.tar.xz"
  - tar -xJf libpng-$LIBPNG_VERSION.tar.xz
  - cd libpng-$LIBPNG_VERSION
  - ls
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - sudo find /usr/lib -name 'libpng*'
  - mkdir -p $BUILD

after_script:
  - cp -R $TRAVIS_BUILD_DIR/examples/burro.png .
  - export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH
  - ./pngtest
